plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

title:
    - ielliott.io

description:
    - Isaac Elliott's personal blog

social:
    name: Isaac Elliott
    links:
        - www.linkedin.com/in/ielliott95
        - www.github.com/lightandlight

defaults:
    -
      scope:
        path: "talks"
      values:
        layout: "default"
